# Day 12

The space near Jupiter is not a very safe place; you need to be careful of a big distracting red spot, extreme radiation, and a whole lot of moons swirling around. You decide to start by tracking the four largest moons: Io, Europa, Ganymede, and Callisto.

After a brief scan, you calculate the position of each moon (your puzzle input). You just need to simulate their motion so you can avoid them.

Each moon has a 3-dimensional position (x, y, and z) and a 3-dimensional velocity. The position of each moon is given in your scan; the x, y, and z velocity of each moon starts at 0.

Simulate the motion of the moons in time steps. Within each time step, first update the velocity of every moon by applying gravity. Then, once all moons' velocities have been updated, update the position of every moon by applying velocity. Time progresses by one step once all of the positions are updated.

To apply gravity, consider every pair of moons. On each axis (x, y, and z), the velocity of each moon changes by exactly +1 or -1 to pull the moons together. For example, if Ganymede has an x position of 3, and Callisto has a x position of 5, then Ganymede's x velocity changes by +1 (because 5 > 3) and Callisto's x velocity changes by -1 (because 3 < 5). However, if the positions on a given axis are the same, the velocity on that axis does not change for that pair of moons.

Once all gravity has been applied, apply velocity: simply add the velocity of each moon to its own position. For example, if Europa has a position of x=1, y=2, z=3 and a velocity of x=-2, y=0,z=3, then its new position would be x=-1, y=2, z=6. This process does not modify the velocity of any moon.

Then, it might help to calculate the total energy in the system. The total energy for a single moon is its potential energy multiplied by its kinetic energy. A moon's potential energy is the sum of the absolute values of its x, y, and z position coordinates. A moon's kinetic energy is the sum of the absolute values of its velocity coordinates. Below, each line shows the calculations for a moon's potential energy (pot), kinetic energy (kin), and total energy:

</pre>

**What is the total energy in the system after simulating the moons given in your scan for 1000 steps?**

In [121]:
# Import the moons and their gravities

moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])

In [183]:
import numpy as np

def apply_gravity(moons, velocities):
    for time in range(10):
        print(f"moons: {moons}, velocities {velocities}")
        moons_copy = moons.copy()
        print(f"moons_copy is {moons_copy}")
        velocities_copy = velocities.copy()
        for i in range(3):
            for position in range(3):
                if moons[i][position] < moons[i+1][position]:
                    moons[i][position] += 1
                    moons[i+1][position] -= 1
                elif moons[i][position] > moons[i+1][position]:
                    moons[i][position] -= 1
                    moons[i+1][position] += 1
        for j in range(2):
            for position in range(3):
                if moons[j][position] < moons[j+2][position]:
                    moons[j][position] += 1
                    moons[j+2][position] -= 1
                elif moons[j][position] > moons[j+2][position]:
                    moons[j][position] -= 1
                    moons[j+2][position] += 1
        for position in range(3):
            if moons[0][position] < moons[3][position]:
                moons[0][position] += 1
                moons[3][position] -= 1
            elif moons[0][position] > moons[3][position]:
                moons[0][position] -= 1
                moons[3][position] += 1
        for i in range(4):
            moons[i] += velocities_copy[i]
            velocities[i] = moons[i] - moons_copy[i]
    #return moons, velocities

In [179]:
# Import the moons and their gravities

moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity(moons,velocities)

moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]]
moons: [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]], velocities [[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-1  1 -3]]
[[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]]
moons: [[ 11 -12  11]
 [  4  -5   7]
 [  5 -12   9]
 [  9 -12   9]], velocities [[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-2  1 -6]]
[[ 11 -12  11]
 [  4  -5   7]
 [  5 -12   9]
 [  9 -12   9]]
moons: [[  8 -11   9]
 [  6  -8   8]
 [  7 -11  10]
 [  6 -10   3]], velocities [[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-3  2 -6]]
[[  8 -11   9]
 [  6  -8   8]
 [  7 -11  10]
 [  6 -10   3]]
moons: [[  7 -10   7]
 [  7 -10   9]
 [  7 -10   8]
 [  3  -8   0]], velocities [[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-3  2 -3]]
[[  7 -10   7]
 [  7 -10   9]
 [  7 -10   8]
 [  3  -8   0]]
moons: [[  5 -10   6]
 [  6  -9   7]
 [  7 -10   8]
 [  3  -7 

In [166]:
def compute_energy(f):
    potential_energy = []
    kinetic_energy = []
    total_energy = 0
    for moon in moons:
        moon_energy = abs(moon[0]) + abs(moon[1]) + abs(moon[2])
        potential_energy.append(moon_energy)
    for velocity in velocities:
        velocity_energy = abs(velocity[0]) + abs(velocity[1]) + abs(velocity[2])
        kinetic_energy.append(velocity_energy)
    for i in range(4):
        total_energy += potential_energy[i] * kinetic_energy[i]
    print(f"The total energy is {total_energy}")

In [167]:
moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
compute_energy(apply_gravity(moons, velocities))



moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons: [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]], velocities [[-3 -1 -1]
 [ 1 -3  3]
 [ 3  3  1]
 [-1  1 -3]]
moons: [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]], velocities [[-3 -1 -1]
 [ 1 -3  3]
 [ 3  3  1]
 [-1  1 -3]]
moons: [[  8 -13  10]
 [  5  -8  10]
 [  8  -9  10]
 [  9 -12   9]], velocities [[-6  0 -2]
 [ 2 -6  6]
 [ 6  5  2]
 [-2  1 -6]]
moons: [[  8 -13  10]
 [  5  -8  10]
 [  8  -9  10]
 [  9 -12   9]], velocities [[-6  0 -2]
 [ 2 -6  6]
 [ 6  5  2]
 [-2  1 -6]]
moons: [[  1 -10   8]
 [ 10 -16  16]
 [ 13  -6  12]
 [  6 -10   3]], velocities [[-7  3 -2]
 [ 5 -8  6]
 [ 5  3  2]
 [-3  2 -6]]
moons: [[  1 -10   8]
 [ 10 -16  16]
 [ 13  -6  12]
 [  6 -10   3]], velocities [[-7  3 -2]
 [ 5 -8  6]
 [ 5  3  2]
 [-3  2 -6]]
moons: [[ -3  -7   7]
 [ 14 -21  19]
 [ 15  -6  13]
 [  4  -8   0]], velocities [[-4  3 -1]
 [ 4 -5  3]
 [ 2 

In [185]:
test_moons = np.array([[-1, 0, 2], [2, -10, -7],[4, -8, 8], [3, 5, -1]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity(test_moons,velocities)

moons: [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]]
moons: [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]], velocities [[ 3 -1 -1]
 [ 1  3  3]
 [-2  1 -3]
 [-2 -3  1]]
moons_copy is [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]]
moons: [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]], velocities [[ 3 -2 -2]
 [ 0  4  6]
 [-2  4 -6]
 [-1 -6  2]]
moons_copy is [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]]
moons: [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]], velocities [[ 0 -2 -1]
 [-1  4  5]
 [-1  4 -5]
 [ 2 -6  1]]
moons_copy is [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]]
moons: [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]], velocities [[-3 -1  0]
 [-2  3  2]
 [ 2  1 -2]
 [ 3 -3  0]]
moons_copy is [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]]
moons: [[  0  -6  -1]
 [  0   4   8]
 [ 

In [189]:
test_moons = np.array([[-1, 0, 2], [2, -10, -7],[4, -8, 8], [3, 5, -1]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
compute_energy(apply_gravity(test_moons,velocities))

moons: [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]]
moons: [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]], velocities [[ 3 -1 -1]
 [ 1  3  3]
 [-2  1 -3]
 [-2 -3  1]]
moons_copy is [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]]
moons: [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]], velocities [[ 3 -2 -2]
 [ 0  4  6]
 [-2  4 -6]
 [-1 -6  2]]
moons_copy is [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]]
moons: [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]], velocities [[ 0 -2 -1]
 [-1  4  5]
 [-1  4 -5]
 [ 2 -6  1]]
moons_copy is [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]]
moons: [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]], velocities [[-3 -1  0]
 [-2  3  2]
 [ 2  1 -2]
 [ 3 -3  0]]
moons_copy is [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]]
moons: [[  0  -6  -1]
 [  0   4   8]
 [ 