# Day 12

The space near Jupiter is not a very safe place; you need to be careful of a big distracting red spot, extreme radiation, and a whole lot of moons swirling around. You decide to start by tracking the four largest moons: Io, Europa, Ganymede, and Callisto.

After a brief scan, you calculate the position of each moon (your puzzle input). You just need to simulate their motion so you can avoid them.

Each moon has a 3-dimensional position (x, y, and z) and a 3-dimensional velocity. The position of each moon is given in your scan; the x, y, and z velocity of each moon starts at 0.

Simulate the motion of the moons in time steps. Within each time step, first update the velocity of every moon by applying gravity. Then, once all moons' velocities have been updated, update the position of every moon by applying velocity. Time progresses by one step once all of the positions are updated.

To apply gravity, consider every pair of moons. On each axis (x, y, and z), the velocity of each moon changes by exactly +1 or -1 to pull the moons together. For example, if Ganymede has an x position of 3, and Callisto has a x position of 5, then Ganymede's x velocity changes by +1 (because 5 > 3) and Callisto's x velocity changes by -1 (because 3 < 5). However, if the positions on a given axis are the same, the velocity on that axis does not change for that pair of moons.

Once all gravity has been applied, apply velocity: simply add the velocity of each moon to its own position. For example, if Europa has a position of x=1, y=2, z=3 and a velocity of x=-2, y=0,z=3, then its new position would be x=-1, y=2, z=6. This process does not modify the velocity of any moon.

Then, it might help to calculate the total energy in the system. The total energy for a single moon is its potential energy multiplied by its kinetic energy. A moon's potential energy is the sum of the absolute values of its x, y, and z position coordinates. A moon's kinetic energy is the sum of the absolute values of its velocity coordinates. Below, each line shows the calculations for a moon's potential energy (pot), kinetic energy (kin), and total energy:

</pre>

**What is the total energy in the system after simulating the moons given in your scan for 1000 steps?**

In [3]:
# Import the moons and their gravities

moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])

In [4]:
import numpy as np

def apply_gravity(moons, velocities):
    for time in range(1000):
        for i in range(3):
            for position in range(3):
                if moons[i][position] < moons[i+1][position]:
                    velocities[i][position] += 1
                    velocities[i+1][position] -= 1
                elif moons[i][position] > moons[i+1][position]:
                    velocities[i][position] -= 1
                    velocities[i+1][position] += 1
        for j in range(2):
            for position in range(3):
                if moons[j][position] < moons[j+2][position]:
                    velocities[j][position] += 1
                    velocities[j+2][position] -= 1
                elif moons[j][position] > moons[j+2][position]:
                    velocities[j][position] -= 1
                    velocities[j+2][position] += 1
        for position in range(3):
            if moons[0][position] < moons[3][position]:
                velocities[0][position] += 1
                velocities[3][position] -= 1
            elif moons[0][position] > moons[3][position]:
                velocities[0][position] -= 1
                velocities[3][position] += 1
        for i in range(4):
            moons[i] += velocities[i]
    return moons, velocities

In [5]:
# Import the moons and their gravities
moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity(moons,velocities)

(array([[ 27,  47,  36],
        [ 21,   5,  -3],
        [-63, -29, -12],
        [ 45, -65,  18]]), array([[ 17,  17,  -4],
        [ -1, -15,   4],
        [ -8,   0,  -9],
        [ -8,  -2,   9]]))

In [6]:
def compute_energy(f):
    potential_energy = []
    kinetic_energy = []
    total_energy = 0
    for moon in moons:
        moon_energy = abs(moon[0]) + abs(moon[1]) + abs(moon[2])
        potential_energy.append(moon_energy)
    for velocity in velocities:
        velocity_energy = abs(velocity[0]) + abs(velocity[1]) + abs(velocity[2])
        kinetic_energy.append(velocity_energy)
    for i in range(4):
        total_energy += potential_energy[i] * kinetic_energy[i]
    print(f"The total energy is {total_energy}")

In [7]:
moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
compute_energy(apply_gravity(moons, velocities))

The total energy is 8960


## Part Two:

All this drifting around in space makes you wonder about the nature of the universe. Does history really repeat itself? You're curious whether the moons will ever return to a previous state.

Determine the number of steps that must occur before all of the moons' positions and velocities exactly match a previous point in time.


**How many steps does it take to reach the first state that exactly matches a previous state?** 


In [12]:
#from collections import defaultdict
import numpy as np

def apply_gravity_and_determine_cycles(moons, velocities):
    initial_moons = np.array([[-1,0, 2], [2, -10, -7], [4, -8, 8], [3,5, -1]])
    #initial_moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
    initial_velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
    periods_of_axes = {}
    time = 0
    while len(periods_of_axes) < 3:
        time+= 1
        for i in range(3):
            for position in range(3):
                if moons[i][position] < moons[i+1][position]:
                    velocities[i][position] += 1
                    velocities[i+1][position] -= 1
                elif moons[i][position] > moons[i+1][position]:
                    velocities[i][position] -= 1
                    velocities[i+1][position] += 1
        for j in range(2):
            for position in range(3):
                if moons[j][position] < moons[j+2][position]:
                    velocities[j][position] += 1
                    velocities[j+2][position] -= 1
                elif moons[j][position] > moons[j+2][position]:
                    velocities[j][position] -= 1
                    velocities[j+2][position] += 1
        for position in range(3):
            if moons[0][position] < moons[3][position]:
                velocities[0][position] += 1
                velocities[3][position] -= 1
            elif moons[0][position] > moons[3][position]:
                velocities[0][position] -= 1
                velocities[3][position] += 1
        for k in range(4):
            count = 0
            moons[k] += velocities[k]
            
        for axis in range(3):
            count = 0
            for i, moon in enumerate(moons):
                if moon[axis] == initial_moons[i][axis]:
                    count +=1
            if count == 4:
                if axis not in periods_of_axes.keys():
                    periods_of_axes[axis] = time
                    print(periods_of_axes)
                    print(f"This is the position of the moons when the moons align on axis {axis}")
                    print(moons)
                #if axis not in periods_of_axes and initial_moons[axis] == [m[axis] for m in moons]: 
                #periods_of_axes[axis] = time
    
    

In [11]:
moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity_and_determine_cycles(moons, velocities)

{0: 56343}
This is the position of the moons when the moons align on axis 0
[[  17  324  539]
 [   2 -357 -169]
 [  -1   79 -313]
 [  12  -88  -18]]
{0: 56343, 2: 193051}
This is the position of the moons when the moons align on axis 2
[[ 135  972   13]
 [  53 -170    1]
 [ -99 -409    7]
 [ -59 -435   18]]
{0: 56343, 2: 193051, 1: 231613}
This is the position of the moons when the moons align on axis 1
[[ 102  -12   52]
 [-128    1   64]
 [  22  -17    5]
 [  34  -14  -82]]


In [90]:
from math import gcd # Python versions 3.5 and above
from functools import reduce # Python version 3.x

def lcm(denominators):
    return reduce(lambda a,b: a*b // gcd(a,b), denominators)

In [14]:
test_moons = np.array([[-1,0, 2], [2, -10, -7], [4, -8, 8], [3,5, -1]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity_and_determine_cycles(test_moons, velocities)

{0: 17}
This is the position of the moons when the moons align on axis 0
[[-1  1 -6]
 [ 2 -8  1]
 [ 4 -6  0]
 [ 3  0  7]]
{0: 17, 1: 27}
This is the position of the moons when the moons align on axis 1
[[  5   0  -4]
 [  2 -10  -1]
 [  0  -8   2]
 [  1   5   5]]
{0: 17, 1: 27, 2: 43}
This is the position of the moons when the moons align on axis 2
[[ 2 -7  2]
 [ 1  2 -7]
 [ 3 -1  8]
 [ 2 -7 -1]]


In [79]:
randomNumbers = [112685,386101,463225]

In [80]:
lcm(randomNumbers)

4030779314334325