# Day 12

The space near Jupiter is not a very safe place; you need to be careful of a big distracting red spot, extreme radiation, and a whole lot of moons swirling around. You decide to start by tracking the four largest moons: Io, Europa, Ganymede, and Callisto.

After a brief scan, you calculate the position of each moon (your puzzle input). You just need to simulate their motion so you can avoid them.

Each moon has a 3-dimensional position (x, y, and z) and a 3-dimensional velocity. The position of each moon is given in your scan; the x, y, and z velocity of each moon starts at 0.

Simulate the motion of the moons in time steps. Within each time step, first update the velocity of every moon by applying gravity. Then, once all moons' velocities have been updated, update the position of every moon by applying velocity. Time progresses by one step once all of the positions are updated.

To apply gravity, consider every pair of moons. On each axis (x, y, and z), the velocity of each moon changes by exactly +1 or -1 to pull the moons together. For example, if Ganymede has an x position of 3, and Callisto has a x position of 5, then Ganymede's x velocity changes by +1 (because 5 > 3) and Callisto's x velocity changes by -1 (because 3 < 5). However, if the positions on a given axis are the same, the velocity on that axis does not change for that pair of moons.

Once all gravity has been applied, apply velocity: simply add the velocity of each moon to its own position. For example, if Europa has a position of x=1, y=2, z=3 and a velocity of x=-2, y=0,z=3, then its new position would be x=-1, y=2, z=6. This process does not modify the velocity of any moon.

Then, it might help to calculate the total energy in the system. The total energy for a single moon is its potential energy multiplied by its kinetic energy. A moon's potential energy is the sum of the absolute values of its x, y, and z position coordinates. A moon's kinetic energy is the sum of the absolute values of its velocity coordinates. Below, each line shows the calculations for a moon's potential energy (pot), kinetic energy (kin), and total energy:

</pre>

**What is the total energy in the system after simulating the moons given in your scan for 1000 steps?**

In [121]:
# Import the moons and their gravities

moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])

In [5]:
import numpy as np

def apply_gravity(moons, velocities):
    for time in range(1000):
        print(f"moons: {moons}, velocities {velocities}")
        moons_copy = moons.copy()
        print(f"moons_copy is {moons_copy}")
        velocities_copy = velocities.copy()
        for i in range(3):
            for position in range(3):
                if moons[i][position] < moons[i+1][position]:
                    velocities[i][position] += 1
                    velocities[i+1][position] -= 1
                elif moons[i][position] > moons[i+1][position]:
                    velocities[i][position] -= 1
                    velocities[i+1][position] += 1
        for j in range(2):
            for position in range(3):
                if moons[j][position] < moons[j+2][position]:
                    velocities[j][position] += 1
                    velocities[j+2][position] -= 1
                elif moons[j][position] > moons[j+2][position]:
                    velocities[j][position] -= 1
                    velocities[j+2][position] += 1
        for position in range(3):
            if moons[0][position] < moons[3][position]:
                velocities[0][position] += 1
                velocities[3][position] -= 1
            elif moons[0][position] > moons[3][position]:
                velocities[0][position] -= 1
                velocities[3][position] += 1
        for i in range(4):
            moons[i] += velocities_copy[i]
            #velocities[i] = moons[i] - moons_copy[i]
    return moons, velocities

In [6]:
# Import the moons and their gravities

moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity(moons,velocities)

moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]]
moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[-3 -1 -1]
 [ 1 -3  3]
 [ 3  3  1]
 [-1  1 -3]]
moons_copy is [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]]
moons: [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]], velocities [[-6 -2 -2]
 [ 2 -6  6]
 [ 6  6  2]
 [-2  2 -6]]
moons_copy is [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]]
moons: [[  8 -15  10]
 [  5  -8  10]
 [  8  -8  10]
 [  9 -11   9]], velocities [[-9 -2 -3]
 [ 3 -9  9]
 [ 9  9  3]
 [-3  2 -9]]
moons_copy is [[  8 -15  10]
 [  5  -8  10]
 [  8  -8  10]
 [  9 -11   9]]
moons: [[ -1 -17   7]
 [  8 -17  19]
 [ 17   1  13]
 [  6  -9   0]], velocities [[ -9   1  -4]
 [  6 -11   8]
 [  9   7   2]
 [ -6   3  -6]]
moons_copy is [[ -1 -17   7]
 [  8 -17  19]
 [ 17   1  

 [-864  -41  458]]
moons: [[-173  730 -471]
 [ 759 -800  899]
 [ 328   20 -873]
 [-884    8  484]], velocities [[ 23   6 -35]
 [ 40   0 -17]
 [-46 -56  27]
 [-17  50  25]]
moons_copy is [[-173  730 -471]
 [ 759 -800  899]
 [ 328   20 -873]
 [-884    8  484]]
moons: [[-150  736 -506]
 [ 799 -800  882]
 [ 282  -36 -846]
 [-901   58  509]], velocities [[ 24   3 -34]
 [ 37   3 -20]
 [-47 -57  30]
 [-14  51  24]]
moons_copy is [[-150  736 -506]
 [ 799 -800  882]
 [ 282  -36 -846]
 [-901   58  509]]
moons: [[-126  739 -540]
 [ 836 -797  862]
 [ 235  -93 -816]
 [-915  109  533]], velocities [[ 25   0 -33]
 [ 34   6 -23]
 [-48 -56  33]
 [-11  50  23]]
moons_copy is [[-126  739 -540]
 [ 836 -797  862]
 [ 235  -93 -816]
 [-915  109  533]]
moons: [[-101  739 -573]
 [ 870 -791  839]
 [ 187 -149 -783]
 [-926  159  556]], velocities [[ 26  -3 -32]
 [ 31   9 -26]
 [-49 -55  36]
 [ -8  49  22]]
moons_copy is [[-101  739 -573]
 [ 870 -791  839]
 [ 187 -149 -783]
 [-926  159  556]]
moons: [[ -75  736 -6

 [  999  -254  -205]]
moons: [[ 1038 -1507   319]
 [ -692  1501 -1238]
 [-1367   283  1235]
 [ 1051  -319  -277]], velocities [[-67  14  64]
 [-26  -6  41]
 [ 42  56 -34]
 [ 51 -64 -71]]
moons_copy is [[ 1038 -1507   319]
 [ -692  1501 -1238]
 [-1367   283  1235]
 [ 1051  -319  -277]]
moons: [[  971 -1493   383]
 [ -718  1495 -1197]
 [-1325   339  1201]
 [ 1102  -383  -348]], velocities [[-68  17  63]
 [-25  -9  44]
 [ 45  55 -37]
 [ 48 -63 -70]]
moons_copy is [[  971 -1493   383]
 [ -718  1495 -1197]
 [-1325   339  1201]
 [ 1102  -383  -348]]
moons: [[  903 -1476   446]
 [ -743  1486 -1153]
 [-1280   394  1164]
 [ 1150  -446  -418]], velocities [[-69  20  62]
 [-24 -12  47]
 [ 48  54 -40]
 [ 45 -62 -69]]
moons_copy is [[  903 -1476   446]
 [ -743  1486 -1153]
 [-1280   394  1164]
 [ 1150  -446  -418]]
moons: [[  834 -1456   508]
 [ -767  1474 -1106]
 [-1232   448  1124]
 [ 1195  -508  -487]], velocities [[-70  23  61]
 [-23 -15  50]
 [ 51  53 -43]
 [ 42 -61 -68]]
moons_copy is [[  834

 [ 75 -44 -45]]
moons_copy is [[ 1497 -1114 -1590]
 [ 1119  1176  -613]
 [-1260 -1824   778]
 [-1326  1720  1464]]
moons: [[ 1548 -1176 -1538]
 [ 1029  1232  -698]
 [-1296 -1774   856]
 [-1251  1676  1419]], velocities [[ 48 -61  55]
 [-91  55 -84]
 [-35  53  77]
 [ 78 -47 -48]]
moons_copy is [[ 1548 -1176 -1538]
 [ 1029  1232  -698]
 [-1296 -1774   856]
 [-1251  1676  1419]]
moons: [[ 1596 -1237 -1483]
 [  938  1287  -782]
 [-1331 -1721   933]
 [-1173  1629  1371]], velocities [[ 45 -60  58]
 [-92  54 -83]
 [-32  56  76]
 [ 79 -50 -51]]
moons_copy is [[ 1596 -1237 -1483]
 [  938  1287  -782]
 [-1331 -1721   933]
 [-1173  1629  1371]]
moons: [[ 1641 -1297 -1425]
 [  846  1341  -865]
 [-1363 -1665  1009]
 [-1094  1579  1320]], velocities [[ 42 -59  61]
 [-93  53 -82]
 [-29  59  75]
 [ 80 -53 -54]]
moons_copy is [[ 1641 -1297 -1425]
 [  846  1341  -865]
 [-1363 -1665  1009]
 [-1094  1579  1320]]
moons: [[ 1683 -1356 -1364]
 [  753  1394  -947]
 [-1392 -1606  1084]
 [-1014  1526  1266]], 

(array([[  227,  -855,  2341],
        [-2806,   575, -1559],
        [  237,  2157,  1303],
        [ 2372, -1919, -2046]]), array([[-74,  71,  37],
        [ -3, -71,  58],
        [ 67,  35, -57],
        [ 10, -35, -38]]))

In [7]:
def compute_energy(f):
    potential_energy = []
    kinetic_energy = []
    total_energy = 0
    for moon in moons:
        moon_energy = abs(moon[0]) + abs(moon[1]) + abs(moon[2])
        potential_energy.append(moon_energy)
    for velocity in velocities:
        velocity_energy = abs(velocity[0]) + abs(velocity[1]) + abs(velocity[2])
        kinetic_energy.append(velocity_energy)
    for i in range(4):
        total_energy += potential_energy[i] * kinetic_energy[i]
    print(f"The total energy is {total_energy}")

In [8]:
moons = np.array([[17, -12, 13],[2, 1, 1], [-1, -17, 7], [12, -14, 18]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
compute_energy(apply_gravity(moons, velocities))



moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]]
moons: [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]], velocities [[-3 -1 -1]
 [ 1 -3  3]
 [ 3  3  1]
 [-1  1 -3]]
moons_copy is [[ 17 -12  13]
 [  2   1   1]
 [ -1 -17   7]
 [ 12 -14  18]]
moons: [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]], velocities [[-6 -2 -2]
 [ 2 -6  6]
 [ 6  6  2]
 [-2  2 -6]]
moons_copy is [[ 14 -13  12]
 [  3  -2   4]
 [  2 -14   8]
 [ 11 -13  15]]
moons: [[  8 -15  10]
 [  5  -8  10]
 [  8  -8  10]
 [  9 -11   9]], velocities [[-9 -2 -3]
 [ 3 -9  9]
 [ 9  9  3]
 [-3  2 -9]]
moons_copy is [[  8 -15  10]
 [  5  -8  10]
 [  8  -8  10]
 [  9 -11   9]]
moons: [[ -1 -17   7]
 [  8 -17  19]
 [ 17   1  13]
 [  6  -9   0]], velocities [[ -9   1  -4]
 [  6 -11   8]
 [  9   7   2]
 [ -6   3  -6]]
moons_copy is [[ -1 -17   7]
 [  8 -17  19]
 [ 17   1  

 [ 51 -16 -21]]
moons_copy is [[ 434 -165 -276]
 [  66  201 -698]
 [-639 -627  822]
 [ 169  549  191]]
moons: [[ 441 -209 -243]
 [   8  241 -727]
 [-639 -607  839]
 [ 220  533  170]], velocities [[  4 -43  34]
 [-57  39 -26]
 [  3  23  14]
 [ 50 -19 -22]]
moons_copy is [[ 441 -209 -243]
 [   8  241 -727]
 [-639 -607  839]
 [ 220  533  170]]
moons: [[ 445 -252 -209]
 [ -49  280 -753]
 [-636 -584  853]
 [ 270  514  148]], velocities [[  1 -42  35]
 [-56  38 -23]
 [  6  26  11]
 [ 49 -22 -23]]
moons_copy is [[ 445 -252 -209]
 [ -49  280 -753]
 [-636 -584  853]
 [ 270  514  148]]
moons: [[ 446 -294 -174]
 [-105  318 -776]
 [-630 -558  864]
 [ 319  492  125]], velocities [[ -2 -41  36]
 [-55  37 -20]
 [  9  29   8]
 [ 48 -25 -24]]
moons_copy is [[ 446 -294 -174]
 [-105  318 -776]
 [-630 -558  864]
 [ 319  492  125]]
moons: [[ 444 -335 -138]
 [-160  355 -796]
 [-621 -529  872]
 [ 367  467  101]], velocities [[ -5 -40  37]
 [-54  36 -17]
 [ 12  32   5]
 [ 47 -28 -25]]
moons_copy is [[ 444 -33

 [-1426   835  1394]]
moons: [[  259   954 -1260]
 [  809 -1114   161]
 [  398  -766  -298]
 [-1436   884  1436]], velocities [[ 79 -52 -38]
 [  6  46 -55]
 [-78 -42  54]
 [ -7  48  39]]
moons_copy is [[  259   954 -1260]
 [  809 -1114   161]
 [  398  -766  -298]
 [-1436   884  1436]]
moons: [[  338   902 -1298]
 [  815 -1068   106]
 [  320  -808  -244]
 [-1443   932  1475]], velocities [[ 80 -55 -35]
 [  3  49 -56]
 [-79 -41  55]
 [ -4  47  36]]
moons_copy is [[  338   902 -1298]
 [  815 -1068   106]
 [  320  -808  -244]
 [-1443   932  1475]]
moons: [[  418   847 -1333]
 [  818 -1019    50]
 [  241  -849  -189]
 [-1447   979  1511]], velocities [[ 79 -56 -32]
 [  0  52 -57]
 [-78 -40  56]
 [ -1  44  33]]
moons_copy is [[  418   847 -1333]
 [  818 -1019    50]
 [  241  -849  -189]
 [-1447   979  1511]]
moons: [[  497   791 -1365]
 [  818  -967    -7]
 [  163  -889  -133]
 [-1448  1023  1544]], velocities [[ 78 -57 -29]
 [ -3  55 -58]
 [-77 -39  57]
 [  2  41  30]]
moons_copy is [[  497

 [ 27   4   3]]
moons_copy is [[  483    14 -2014]
 [ 2213   144   811]
 [ -548 -2216  -534]
 [-2118  2016  1776]]
moons: [[  554   -64 -2010]
 [ 2167   216   726]
 [ -600 -2214  -456]
 [-2091  2020  1779]], velocities [[ 70 -77   7]
 [-49  71 -86]
 [-51   5  79]
 [ 30   1   0]]
moons_copy is [[  554   -64 -2010]
 [ 2167   216   726]
 [ -600 -2214  -456]
 [-2091  2020  1779]]
moons: [[  624  -141 -2003]
 [ 2118   287   640]
 [ -651 -2209  -377]
 [-2061  2021  1779]], velocities [[ 69 -76  10]
 [-52  70 -87]
 [-50   8  80]
 [ 33  -2  -3]]
moons_copy is [[  624  -141 -2003]
 [ 2118   287   640]
 [ -651 -2209  -377]
 [-2061  2021  1779]]
moons: [[  693  -217 -1993]
 [ 2066   357   553]
 [ -701 -2201  -297]
 [-2028  2019  1776]], velocities [[ 68 -75  13]
 [-55  69 -88]
 [-49  11  81]
 [ 36  -5  -6]]
moons_copy is [[  693  -217 -1993]
 [ 2066   357   553]
 [ -701 -2201  -297]
 [-2028  2019  1776]]
moons: [[  761  -292 -1980]
 [ 2011   426   465]
 [ -750 -2190  -216]
 [-1992  2014  1770]], 

In [2]:
test_moons = np.array([[-1, 0, 2], [2, -10, -7],[4, -8, 8], [3, 5, -1]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
apply_gravity(test_moons,velocities)

moons: [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]]
moons: [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]], velocities [[ 3 -1 -1]
 [ 1  3  3]
 [-3  1 -3]
 [-1 -3  1]]
moons_copy is [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]]
moons: [[ 2 -1  1]
 [ 3 -7 -4]
 [ 1 -7  5]
 [ 2  2  0]], velocities [[ 6 -2 -2]
 [ 2  6  6]
 [-6  2 -6]
 [-2 -6  2]]
moons_copy is [[ 2 -1  1]
 [ 3 -7 -4]
 [ 1 -7  5]
 [ 2  2  0]]
moons: [[ 8 -3 -1]
 [ 5 -1  2]
 [-5 -5 -1]
 [ 0 -4  2]], velocities [[ 6 -3 -3]
 [-1  8  9]
 [-3  4 -9]
 [-2 -9  3]]
moons_copy is [[ 8 -3 -1]
 [ 5 -1  2]
 [-5 -5 -1]
 [ 0 -4  2]]
moons: [[ 14  -6  -4]
 [  4   7  11]
 [ -8  -1 -10]
 [ -2 -13   5]], velocities [[ 3 -4 -1]
 [-2  5  7]
 [ 0  7 -7]
 [-1 -8  1]]
moons_copy is [[ 14  -6  -4]
 [  4   7  11]
 [ -8  -1 -10]
 [ -2 -13   5]]
moons: [[ 17 -10  -5]
 [  2  12  18]
 [ 

(array([[-11, -15,   5],
        [-11,  -2,   8],
        [ 23,  20,  -7],
        [  7, -16,  -4]]), array([[ -9,   2,   3],
        [  4,  -7, -11],
        [  2,  -5,  11],
        [  3,  10,  -3]]))

In [189]:
test_moons = np.array([[-1, 0, 2], [2, -10, -7],[4, -8, 8], [3, 5, -1]])
velocities = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])
compute_energy(apply_gravity(test_moons,velocities))

moons: [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]], velocities [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
moons_copy is [[ -1   0   2]
 [  2 -10  -7]
 [  4  -8   8]
 [  3   5  -1]]
moons: [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]], velocities [[ 3 -1 -1]
 [ 1  3  3]
 [-2  1 -3]
 [-2 -3  1]]
moons_copy is [[ 2 -1  1]
 [ 3 -7 -4]
 [ 2 -7  5]
 [ 1  2  0]]
moons: [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]], velocities [[ 3 -2 -2]
 [ 0  4  6]
 [-2  4 -6]
 [-1 -6  2]]
moons_copy is [[ 5 -3 -1]
 [ 3 -3  2]
 [ 0 -3 -1]
 [ 0 -4  2]]
moons: [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]], velocities [[ 0 -2 -1]
 [-1  4  5]
 [-1  4 -5]
 [ 2 -6  1]]
moons_copy is [[  5  -5  -2]
 [  2   1   7]
 [ -1   1  -6]
 [  2 -10   3]]
moons: [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]], velocities [[-3 -1  0]
 [-2  3  2]
 [ 2  1 -2]
 [ 3 -3  0]]
moons_copy is [[  2  -6  -2]
 [  0   4   9]
 [  1   2  -8]
 [  5 -13   3]]
moons: [[  0  -6  -1]
 [  0   4   8]
 [ 